import { defineCollection, z } from "astro:content";
import { glob, file } from "astro/loaders";

/** Every collection here is GENERATED by brain's scripts/portfolio_sync.py.
 *  Schemas are the contract between the vault and the site — if a sync writes a field
 *  this schema doesn't know, the build fails loudly rather than dropping it silently. */

const projects = defineCollection({
  loader: glob({ base: "./src/content/projects", pattern: "**/*.md" }),
  schema: z.object({
    title: z.string(),
    summary: z.string(),
    started: z.string().optional(),
    ended: z.string().optional(),
    status: z.enum(["active", "paused", "done"]).default("done"),
    featured: z.boolean().default(false),
    order: z.number().default(50),
    tools: z.array(z.string()).default([]),
    metrics: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    repo: z.string().url().optional(),
    /** true when the write-up is the deliverable (private repo, employer work) */
    writeupOnly: z.boolean().default(false),
    image: z.string().optional(),
    imageAlt: z.string().optional(),
  }),
});

const posts = defineCollection({
  loader: glob({ base: "./src/content/posts", pattern: "**/*.{md,mdx}" }),
  schema: z.object({
    title: z.string(),
    date: z.string(),
    summary: z.string(),
    tags: z.array(z.string()).default([]),
    draft: z.boolean().default(false),
  }),
});

const experience = defineCollection({
  loader: glob({ base: "./src/content/experience", pattern: "**/*.md" }),
  schema: z.object({
    company: z.string(),
    title: z.string(),
    start: z.string(),
    end: z.string().optional(),
    location: z.string().optional(),
    kind: z.enum(["job", "education"]).default("job"),
    order: z.number().default(50),
    bullets: z.array(z.string()).default([]),
  }),
});

const timeline = defineCollection({
  loader: glob({ base: "./src/content/timeline", pattern: "**/*.md" }),
  schema: z.object({
    date: z.string(),
    end: z.string().optional(),
    title: z.string(),
    type: z.enum(["education", "job", "project", "milestone", "cert", "talk", "post"]),
    project: z.string().optional(),
  }),
});

const resume = defineCollection({
  loader: glob({ base: "./src/content/resume", pattern: "**/*.md" }),
  schema: z.object({ title: z.string().default("Résumé"), updated: z.string().optional() }),
});

export const collections = { projects, posts, experience, timeline, resume };
