name: Build & Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/deploy.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - run: npm run build
        name: Build (export → out/)

      - run: |
          rm -rf docs
          mv out docs
          python -c "open('docs/.nojekyll','a').close()"
        name: Prepare docs/

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - uses: actions/deploy-pages@v1
