# .github/workflows/deploy.yml
name: Build & Deploy to GitHub Pages
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/deploy.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (export static into out/)
        run: npm run build

      - name: Prepare docs folder
        run: |
          rm -rf docs
          mv out docs
          # disable Jekyll so _next/ assets aren’t ignored
          python -c "open('docs/.nojekyll','a').close()"

      - name: Commit and push docs
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add docs
          git commit -m "chore: deploy static site [skip ci]" || echo "No changes to commit"
          git push origin main
