name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/deploy.yml'

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (export static into out/)
        run: npm run build

      - name: Prepare docs folder
        run: |
          rm -rf docs
          mv out docs

      - name: Disable Jekyll
        run: |
          # Create an empty .nojekyll at the root of docs
          python -c "open('docs/.nojekyll','a').close()"

      - name: Commit & push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "chore: deploy static site [skip ci]" || echo "No changes to commit"
          git push origin main
